### ISSUE TITLE
App is closing in Android10; App icon not visible in Android9

### ISSUE THREAD

**Issue by lntsudhakar** [skb1129/react-native-change-icon#17] opened 2020-06-08 06:52 UTC
**Platform**
 - [x] Android

**Description**
1 - In Android10 (Emulator) app is closing after changing the icon.
2 - In Android 9 - Pie (Samsung S8 real device) icons are not visible.

**Device:**
 - Device: Issue 1 - [Nexus_5X_API_29_x86] Emulator
 - Device: Issue 2 - [Samsung S8_API_28] Real device

**Versions**
 - react-native: [0.60.22]
 - react-native-change-icon: [2.0.3]

**Code Snippet**
 AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.sample">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <!-- Add this SplashActivity -->
        <activity
          android:name=".SplashActivity"
          android:theme="@style/SplashTheme"
          android:label="@string/app_name"
          android:exported="true">
        </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:enabled="true"
        android:configChanges="keyboard|keyboardHidden|screenSize"
        android:windowSoftInputMode="adjustNothing"
        android:exported="true"
        android:screenOrientation="sensorPortrait">
      </activity>

      <activity-alias
            android:name="com.sample.MainActivityone"
            android:enabled="true"
            android:icon="@mipmap/one"
            android:label="one"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

        <activity-alias
            android:name="com.sample.MainActivitytwo"
            android:enabled="false"
            android:icon="@mipmap/two"
            android:label="two"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

        <activity-alias
            android:name="com.sample.MainActivitythree"
            android:enabled="false"
            android:icon="@mipmap/three"
            android:label="three"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by skb1129** [comment] 2020-06-08 08:09
@lntsudhakar, please try replacing your activity with this:
```
<activity
          android:name=".MainActivity"
          android:configChanges="keyboard|keyboardHidden|screenSize"
          android:exported="true"
          android:label="@string/app_name"
          android:screenOrientation="sensorPortrait"
          android:windowSoftInputMode="adjustNothing">
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
</activity>
```
I tried the same on both Android 9 & 10 simulators, it is working fine for me.

**Comment by lntsudhakar** [comment] 2020-06-08 08:44
In Android 10 simulator its working fine. But in Android 9 after changing, app is closing and two instance of app is created.

**Comment by skb1129** [comment] 2020-06-08 09:52
@lntsudhakar, I have updated the comment, can you try again, please?

**Comment by lntsudhakar** [comment] 2020-06-08 09:59
@skb1129, Still the same issue

**Comment by skb1129** [comment] 2020-06-08 10:10
@lntsudhakar Can you try in on the Samsung S8 real device. I feel like this might just be a simulator issue.

**Comment by lntsudhakar** [comment] 2020-06-08 10:17
@skb1129  In Samsung S8 (Android 9) real device the App Icon itself is not visible.

**Comment by lntsudhakar** [comment] 2020-06-08 10:28
@skb1129  Is it working for you in real device for Android 9 and 10?

**Comment by skb1129** [comment] 2020-06-08 10:55
@lntsudhakar I don't have any Android device with me that I can test it on.

**Comment by skb1129** [comment] 2020-06-08 11:07
@lntsudhakar, can you please once try running a release version of the application. I tried it and it is working now on both Android 10 & 9 simulators.

**Comment by lntsudhakar** [comment] 2020-06-08 13:56
@skb1129 Still the same issue in emulator. In Real device Android 9 the icon is not visible, and in real device Android10 the app is getting closed.

**Comment by skb1129** [comment] 2020-06-08 15:06
@lntsudhakar I don't have enough bandwidth and resources to work on this issue.

The icon changing experience in Android is not actually supported by Android itself and what I did in this package is a workaround, issues are always expected.

I'll mark this issue as help wanted and will continue working on this when I have the bandwidth.

**Comment by anvitad-sdei** [comment] 2020-06-26 06:19
I have integrated this plugin for both Android and iOS platforms. And It's work fine for me changing icons accordingly.
But my finding this:

iOS: App icon change as per my requirement with a nice popup (You have changed your app icons) I like this.
Android: App icon change as per my requirement but not showing popup I need to show the popup. Instead of popup app is going background.

Is there any solution for android for this issue?

**Comment by skb1129** [comment] 2020-06-26 07:48
@anvitad-sdei The `changeIcon` function returns a promise when the task is complete. You wait for that promise to fulfill and then use the React-Native internal Alert module to display an alert just for android.
This is how we handle it in our application.

**Comment by anvitad-sdei** [comment] 2020-06-26 14:16
@skb1129 Can you please send me the working code example which I have got icon name in console.log, In this plugin document, I'm unable to see any example related this.

**Comment by skb1129** [comment] 2020-06-27 11:36
@anvitad-sdei, This issue is regarding that problem only. This is happening on Android 10.

**Comment by Vidya-K1** [comment] 2020-07-20 07:33
@skb1129 Hi, We used your package for production build. We are facing android app closing issue. Is there anything updates on it? It is very urgent due to release.

**Comment by Sabari-C** [comment] 2020-07-20 07:35
@skb1129 Hi, We used your package for production build. We are facing android app closing issue. Is there anything updates on it? It is very urgent due to release.

**Comment by skb1129** [comment] 2020-07-21 09:44
@Sabari-C No updates yet, I still don't have the bandwidth and the resources to work on this.
You are welcome to create a PR if you are able to get a solution for this, I can review and merge that as soon as possible.

**Comment by MuhammetAdamoglu** [comment] 2020-10-26 07:45
Hi @skb1129 , when the icon changes the application dies. I add the error that the application gives in the icon change below. Maybe this error will help you. I'm trying to fix this.
<img width="1335" alt="Ekran Resmi 2020-10-26 10 45 03" src="https://user-images.githubusercontent.com/35458717/97146100-f1c59a80-176f-11eb-9c34-d90f51b745c5.png">

**Comment by ensargunesdogdu** [comment] 2021-01-19 11:21
I tried many things. No result for android 10. App still closing. Only way to do it when app enable the icon first then when the app is on Pause disable the other component.It's still kill the app but at least user does not experience it. See the code below. If it's okey for you guys. I can create a PR.

`
class ChangeIconModule(reactContext: ReactApplicationContext, private val packageName: String) : ReactContextBaseJavaModule(reactContext), Application.ActivityLifecycleCallbacks {
    private var classToKill: String = ""
    private var componentClass: String = ""
    private var iconChanged: Boolean = false;
    override fun getName(): String {
        return "ChangeIcon"
    }

    @ReactMethod
    fun changeIcon(enableIcon: String, promise: Promise) {
        val activity: Activity? = currentActivity
        if (activity == null || enableIcon.isEmpty()) {
            promise.reject("Icon string is empty.")
            return
        }
        if (componentClass.isEmpty()) componentClass = activity.componentName.className
        val activeClass = "$packageName.MainActivity$enableIcon"
        if (componentClass == activeClass) {
            promise.reject("Icon already in use.")
            return
        }
        promise.resolve(true)
        activity.packageManager.setComponentEnabledSetting(
                ComponentName(packageName, activeClass),
                PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
                PackageManager.DONT_KILL_APP
        )
        classToKill = componentClass;
        componentClass = activeClass
        if (Build.VERSION.SDK_INT < 29) {
            activity.packageManager.setComponentEnabledSetting(
                    ComponentName(packageName, componentClass),
                    PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                    PackageManager.DONT_KILL_APP
            )
        } else {
            activity.application.registerActivityLifecycleCallbacks(this)
            iconChanged = true;
        }
    }

    private fun fullFillChange() {
        if (iconChanged) {
            val activity: Activity? = currentActivity
            if (activity == null) {
                return
            }
            activity.packageManager.setComponentEnabledSetting(
                    ComponentName(packageName, classToKill),
                    PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                    PackageManager.DONT_KILL_APP
            )
            iconChanged = false;
        }
    }

    override fun onActivityPaused(activity: Activity) {
        fullFillChange();
    }

    override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
    }

    override fun onActivityStarted(activity: Activity) {
    }

    override fun onActivityResumed(activity: Activity) {
    }

    override fun onActivityStopped(activity: Activity) {
    }

    override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {
    }

    override fun onActivityDestroyed(activity: Activity) {
    }
}
`

**Comment by skb1129** [comment] 2021-01-20 06:33
@ensargunesdogdu, this seems like an appropriate solution but I would suggest we do not put a check on the SDK version, keep it consistent for all android versions. You can proceed for creating a PR, I'll test and review it before merging.

**Comment by afgarcia86** [comment] 2021-01-27 14:06
I am also experiencing this +1 for update.

**Comment by Victor-Varghese** [comment] 2021-01-27 16:08
I can confirm the changes made by @ensargunesdogdu works like a hack for android 10 . if user minimised the app, it will be killed (not sure why)

But these changes will not work with Android 8 versions. i couldn't even see app icons in some scenarios

**Comment by ensargunesdogdu** [comment] 2021-01-27 18:44
@skb1129 Maybe we should keep the code as it is for supporting smooth experience for older devices. And keep SDK version check logic. Whats your idea ?

**Comment by skb1129** [comment] 2021-02-02 06:13
@ensargunesdogdu Can you try this solution: https://stackoverflow.com/a/62882752.
If this does not work, we can go ahead with your solution.

**Comment by afgarcia86** [comment] 2021-02-03 22:55
@skb1129 you closed this but I don't think we are clear on what we need to change? I am still experiencing the crash when it updates the icon on Android.

**Comment by skb1129** [comment] 2021-02-04 04:05
@afgarcia86 I didn't close this issue, I closed a duplicate issue and referenced that to this issue.

**Comment by skb1129** [comment] 2021-02-10 08:12
@ensargunesdogdu I tried the other solution I mentioned earlier, it does not work. We can move ahead with your solution.
Please create a PR with your solution and tag me as a reviewer. I'll test it and merge it in a couple of days.

**Comment by Victor-Varghese** [comment] 2021-02-10 08:20
@skb1129 can you also check why app is killed when going to background (@ensargunesdogdu  's solution)

**Comment by skb1129** [comment] 2021-02-10 08:41
> @skb1129 can you also check why app is killed when going to background (@ensargunesdogdu  's solution)

That is the hack in his solution. The icon will be changed when the app goes background so the user will not experience the crash.

**Comment by blazk0** [comment] 2021-02-11 13:58
This is happening to me as well, 
on IOS its working great.
on Android, it makes the app go to background mode (the icon is changed tho) and if you click on the app icon while its still in background , white screen is present. (its not a crash the app makes network request but only white screen)

**Comment by skb1129** [comment] 2021-03-22 15:11
Guys I have just released a beta version fixing this issue, please try it once, if this works then I'll create a major release on NPM.

**Comment by afgarcia86** [comment] 2021-05-13 00:15
@skb1129 how do I test the beta version?

**Comment by skb1129** [comment] 2021-05-13 06:45
@afgarcia86 `npm i react-native-change-icon@3.1.0-beta.0`

**Comment by ruairioliverwv** [comment] 2021-05-27 09:41
Hi @skb1129, I tried this out today. Not perfect but definitely improvement on closing the app.

**Comment by skb1129** [comment] 2022-08-18 20:15
Closing as inactive

**Closed by skb1129** 2022-08-18 20:15 UTC
Labels: help wanted

**Comment by gontovnik** [comment] 2023-02-02 11:59
We had a similar issue where the user changed the icon and then tried to buy a subscription. As soon as the Android purchase popup was shown, the app was closing down. This is how we updated `onActivityPaused`
```java
@Override
public void onActivityPaused(Activity activity) {
    final String activityName = activity.getClass().getSimpleName();
    if (activityName.equals("MainActivity")) {
        final Runnable runnable = this::completeIconChange;
        scheduledCompleteIconChange = worker.schedule(runnable, 500, TimeUnit.MILLISECONDS);
    } else if (activityName.equals("ProxyBillingActivity") && scheduledCompleteIconChange != null) {
        scheduledCompleteIconChange.cancel(false);
    }
}
```

And, of course, you'll have to add these two variables to the `ChangeIconModule` class:
```java
private final ScheduledExecutorService worker = Executors.newSingleThreadScheduledExecutor();
private ScheduledFuture<?> scheduledCompleteIconChange = null;
```

Not saying that it is the best fix; it is indeed a hacky fix. But we have no context over how Android app icon change works, and this was a reasonable fix for us.
